name: Build
on:
  workflow_dispatch: {}
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types: [published]

jobs:
  build_appimage:
    permissions:
      actions: read
      security-events: write
      contents: write
    name: Build Ghostty (${{ matrix.arch }})
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - arch: aarch64
            platform: linux/arm64
            runs-on: ubuntu-24.04-arm
          - arch: x86_64
            platform: linux/amd64
            runs-on: ubuntu-24.04
    container:
      image: ${{ matrix.arch == 'aarch64' && 'arm64v8/ubuntu:24.04' || 'ubuntu:24.04' }}
      options: "--privileged --cap-add SYS_ADMIN --device /dev/fuse"
    steps:
      - name: Checkout ghostty-appimage
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Build Env
        run: ./setup.sh

      - name: Build Ghostty
        run: ./build.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ghostty-appimage-${{ matrix.arch }}
          retention-days: 7
          path: /tmp/ghostty-build/Ghostty-*-${{ matrix.arch }}.AppImage*

      - name: Upload binaries to release
        if: ${{ github.event_name == 'release' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /tmp/ghostty-build/Ghostty-*-${{ matrix.arch }}.AppImage*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
